# Generated by Django 2.1.2 on 2018-10-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=32)),
                ('month', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=32)),
            ],
        ),
    ]
